// <auto-generated />
namespace Dept_ItemsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aaa2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aaa2));
        
        string IMigrationMetadata.Id
        {
            get { return "202201020325274_aaa2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
